### PR TITLE
v0.2.9012

### PR DESCRIPTION
**Pull request by hlky**
v0.2.9012

Changelog:
* #162 use init image as control [1]
* controlnet refactor/de-duplicate [2]
* hi-res fix applies correctly after each iteration, instead of after all iterations [3]
* remove legacy code from compvis (stats, info, comments) [4]
* add some typing to compvis
* vram/ram monitor class [5]
* prompt_weights.py test [6]
* read ray temp dir from os environment RAY_TEMP_DIR [7]
* move conditioning to correct device [8]
* no controlnet on pix2pix [9]
* #165 
* #166 

[1] See ticket for details of implementation
[2] required adding control_fakescribbles to controlnet.json, this is the same file/download as control_scribble, the file will not be downloaded twice
[2a] control_hough is the same as control_mlsd. hough is used as the control_type selection as per original gradios, but the model is called mlsd
[3] did not affect stable horde
[4] not used anywhere afaik
[5] see scripts/test_txt2img.py for usage. supports getting current usage, recording usage (start, stop) and recording events e.g. before_load, after_load, inference_start
[6] start of unit tests
[7] requested on discord
[8] setting gpu_id on on load for compvis now should work correctly
[9] noticed errors from my workers trace.log when controlnet is attempted to be applied to pix2pix

### CODE REVIEW

**Comment by hlky** [comment]
controlnet.json changes need to be synced to nataili-model-reference before merge

**Comment by hlky** [comment]
test results (and images) will be shared here

**Comment by hlky** [comment]
Testing for #162 needed, can use original gradio annotators to get the image to use as init for control. These can be added to the test images in `scripts`

**Comment by hlky** [comment]
[test_control.txt](https://github.com/hlky/nataili/files/10834052/test_control.txt)

Init
00726-2641044396_cute_girl_holding_a_giant_NVIDIA_gtx_1080ti_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_detail,_pixiv_trending


Canny
00000-20_DDIM_3423980666_anime-girl

HED
00001-20_DDIM_3693006225_anime-girl

Depth
00002-20_DDIM_1261783757_anime-girl

Normal
00003-20_DDIM_2027437754_anime-girl

Openpose
00004-20_DDIM_11226441_anime-girl

Segmentation
00005-20_DDIM_4111152086_anime-girl

Scribbles
00006-20_DDIM_1778630088_anime-girl

Fake scribbles
00007-20_DDIM_2006218873_anime-girl

Hough
00008-20_DDIM_55528442_anime-girl

**Comment by hlky** [comment]
[test_txt2img.txt](https://github.com/hlky/nataili/files/10834062/test_txt2img.txt)

00000-50_k_lms_1130697785_stylized-art-0-75-dungeons-and-dragons-0-9-male-half-orc-1-1-barbarian-wearing-short

This test is utilizing vram/ram monitor. Note: figures include usage from active horde worker.

**Comment by hlky** [comment]
[test_img2img.txt](https://github.com/hlky/nataili/files/10834069/test_img2img.txt)

Init
00726-2641044396_cute_girl_holding_a_giant_NVIDIA_gtx_1080ti_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_detail,_pixiv_trending


Output
00000-50_k_lms_3558258926_anime-girl-holding-a-giant-nvidia-gtx-1080ti-gpu-graphics-card

**Comment by hlky** [comment]
pix2pix also tested with special case `control_type="scribble"` (scribble as an example)

controlnet is not applied, pix2pix generation continues as normal

[test_pix2pix.txt](https://github.com/hlky/nataili/files/10834092/test_pix2pix.txt)

Init
00726-2641044396_cute_girl_holding_a_giant_NVIDIA_gtx_1080ti_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_detail,_pixiv_trending

Output
00000-50_k_lms_1591892118_make-her-a-brunette

**Comment by hlky** [comment]
[test_txt2img_hires.txt](https://github.com/hlky/nataili/files/10834103/test_txt2img_hires.txt)

00000-50_k_lms_4048658334_stylized-art-0-75-dungeons-and-dragons-0-9-male-half-orc-1-1-barbarian-wearing-short

**Comment by hlky** [comment]
RAY_TEMP_DIR
```
RAY_TEMP_DIR="/tmp/localtemp/ray" python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nataili import enable_local_ray_temp
>>> enable_local_ray_temp.activate()
>>> from nataili.util.voodoo import load_from_plasma
2023-02-26 16:08:58,816 INFO worker.py:1553 -- Started a local Ray instance.
INIT       | Prepared    | Ray temp dir '/tmp/localtemp/ray'
```

**Comment by hlky** [comment]
[test_prompt_weights.txt](https://github.com/hlky/nataili/files/10834119/test_prompt_weights.txt)

**Comment by hlky** [comment]
#162 tests

Init (init as control)
canny

Output
00000-20_DDIM_3596574199_anime-girl

**Comment by hlky** [comment]
Instead of using openpose annotator to detect the pose, it can be drawn

Pose scribbled in mspaint (would work better with more effort put into drawing the pose)
daafaafarqrwrq

00000-20_DDIM_25074994_anime-girl

**Comment by hlky** [comment]
Implications for AI-Horde-Worker

* `init_as_control` can be passed to `compvis.generate` when using control_type
```
compvis.generate(
    prompt,
    init_img=init_image,
    control_type=control_type,
    init_as_control=True,
    ddim_steps=20,
)
```
* set ray local temp with os environment variable `RAY_TEMP_DIR`
* requests for pix2pix with control type will not fail

**Comment by db0** [comment]
What does 'init_as_control' do again?

**Comment by hlky** [comment]
Breakdown of changes

* `ldm/models/diffusion/kdiffusion.py` - gpu_id support/conditioning to correct device
* `nataili/controlnet.json` - sync <-> nataili-model-reference, adds `control_hough` (duplicate of control_mlsd) and control_fakescribbles (duplicate of control_scribble) - these will not download again just a result of the refactor - `hough` is the name of the control type, `mlsd` is the name of the model, `fakescribbles` controltype uses same controlnet model as `scribble`, the difference in control_type name vs controlnet model name was handled manually before
* `nataili/model_manager/compvis.py` - gpu_id support/conditioning to correct device
* `nataili/stable_diffusion/annotation.py` - init_as_control support
* `nataili/stable_diffusion/compvis.py` - adds some typing, removes legacy code, ensures controlnet does not apply to pix2pix, moves device of `cond_stage_model.transformer` and sets `cond_stage_model.device`, controlnet refactor, hi-res fix applies after each iteration (moved one level of indent inwards), low_vram moves to `self.model["device"]` instead of `cuda`
* `nataili/util/monitor.py` - VRAM and RAM monitor, can be implemented directly into inferences classes, supports named events - `monitor.record_event("load_model")` ``monitor.record_event("after_cond_offload")` then `monitor.named_history` is `{'load_model': 4321, 'after_cond_offload': 3124}` also accessible via `monitor.get_event("after_cond_offload")`, `monitor.get_events()`, `monitor.log_events()` etc
* `nataili/util/voodoo.py` - RAY_TEMP_DIR os enviornment support for ray local temp dir
* `scripts/standard_compvis.sh` runs test scripts for txt2img, hi-res fix, img2img and pix2pix
* `scripts/test_control.py` - passes in ControlNetManager to CompVis, verbosity
* `scripts/test_controlnet_{control_type}.py` - used to test controlnet with `init_as_control`

Explanation of `init_as_control`:
* Normally, the init image is processed by the control type's annotator model to produce a control map
* This allows providing the control map directly, otherwise, the control type's annotator model runs on the init image and this produces unintended results
* control maps can be produced using https://github.com/lllyasviel/ControlNet/blob/main/gradio_annotator.py
* support for generating control maps separately can be added [1]

[1] NOTE: control type annotator models add to the resources required for running controlnet, in the future, it could be possible to allow workers to process controlnet annotations as a distinct task, similar to how support for workers running i.e. upscaling, facefixing as distinct steps in a chained request could be added
`request for control type -> init image sent to worker supporting annotation type -> detected map returned/sent to next stage`

**Comment by db0** [comment]
Thanks for the detailed description. Give me a bit of time to go through

**Comment by hlky** [comment]
Will get #165 and #166 fixed for this version

**Comment by db0** [comment]
I run my worker all day. No issues.

**Review by db0 — DISMISSED** [review]

**Review by ResidentChief — APPROVED** [review]
Apart from the controlnet.json file which is pointing at the full models instead of the diffs (shouldn't be an issue given it should be using the online version anyways), this looks sweet and is running on paperspace fine :)

**Review by ResidentChief — APPROVED** [review]

**Review by db0 — APPROVED** [review]

**Pull request merged**
